-- VHDL Entity lab6_lib.Vending_Machine.symbol
--
-- Created:
--          by - zhijiej2.ews (dcl-l440-30.ews.illinois.edu)
--          at - 13:20:43 10/04/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Vending_Machine IS
   PORT( 
      S0 : IN     std_logic;
      S1 : IN     std_logic;
      S2 : IN     std_logic;
      A  : OUT    std_logic;
      P  : OUT    std_logic
   );

-- Declarations

END Vending_Machine ;

--
-- VHDL Architecture lab6_lib.Vending_Machine.struct
--
-- Created:
--          by - zhijiej2.ews (dcl-l440-30.ews.illinois.edu)
--          at - 13:20:43 10/04/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF Vending_Machine IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_3' of 'and'
   dout3 <= dout AND dout1;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'and'
   dout4 <= S2 AND dout2;

   -- ModuleWare code(v1.9) for instance 'U_5' of 'and'
   dout6 <= S1 AND dout1;

   -- ModuleWare code(v1.9) for instance 'U_6' of 'and'
   dout5 <= S2 AND S0;

   -- ModuleWare code(v1.9) for instance 'U_0' of 'inv'
   dout <= NOT(S0);

   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   dout2 <= NOT(S1);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'inv'
   dout1 <= NOT(S2);

   -- ModuleWare code(v1.9) for instance 'U_7' of 'or'
   A <= dout3 OR dout4;

   -- ModuleWare code(v1.9) for instance 'U_8' of 'or'
   P <= dout6 OR dout5;

   -- Instance port mappings.

END struct;
