-- VHDL Entity lab6_lib.Vending_Machine_NAND.symbol
--
-- Created:
--          by - zhijiej2.ews (dcl-l440-30.ews.illinois.edu)
--          at - 13:56:34 10/04/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Vending_Machine_NAND IS
   PORT( 
      S0 : IN     std_logic;
      S1 : IN     std_logic;
      S2 : IN     std_logic;
      A  : OUT    std_logic;
      P  : OUT    std_logic
   );

-- Declarations

END Vending_Machine_NAND ;

--
-- VHDL Architecture lab6_lib.Vending_Machine_NAND.struct
--
-- Created:
--          by - zhijiej2.ews (dcl-l440-30.ews.illinois.edu)
--          at - 13:56:34 10/04/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF Vending_Machine_NAND IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_3' of 'nand'
   dout <= NOT(S0 AND S0);

   -- ModuleWare code(v1.9) for instance 'U_4' of 'nand'
   dout2 <= NOT(S1 AND S1);

   -- ModuleWare code(v1.9) for instance 'U_5' of 'nand'
   dout1 <= NOT(S2 AND S2);

   -- ModuleWare code(v1.9) for instance 'U_6' of 'nand'
   dout3 <= NOT(dout AND dout1);

   -- ModuleWare code(v1.9) for instance 'U_9' of 'nand'
   dout4 <= NOT(S2 AND dout2);

   -- ModuleWare code(v1.9) for instance 'U_10' of 'nand'
   dout5 <= NOT(S1 AND dout1);

   -- ModuleWare code(v1.9) for instance 'U_11' of 'nand'
   dout6 <= NOT(S2 AND S0);

   -- ModuleWare code(v1.9) for instance 'U_12' of 'nand'
   A <= NOT(dout3 AND dout4);

   -- ModuleWare code(v1.9) for instance 'U_13' of 'nand'
   P <= NOT(dout5 AND dout6);

   -- Instance port mappings.

END struct;
