-- VHDL Entity lab4_lib.Full_Adder.symbol
--
-- Created:
--          by - zhijiej2.ews (eceb-2022-28.ews.illinois.edu)
--          at - 19:10:53 09/18/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Full_Adder IS
   PORT( 
      a    : IN     std_logic;
      b    : IN     std_logic;
      cin  : IN     std_logic;
      cout : OUT    std_logic;
      s    : OUT    std_logic
   );

-- Declarations

END Full_Adder ;

--
-- VHDL Architecture lab4_lib.Full_Adder.struct
--
-- Created:
--          by - zhijiej2.ews (eceb-2022-28.ews.illinois.edu)
--          at - 19:10:53 09/18/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY lab4_lib;

ARCHITECTURE struct OF Full_Adder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL f     : std_logic;


   -- Component Declarations
   COMPONENT my_xor
   PORT (
      a : IN     std_logic ;
      b : IN     std_logic ;
      f : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : my_xor USE ENTITY lab4_lib.my_xor;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_4' of 'and'
   dout <= f AND cin;

   -- ModuleWare code(v1.9) for instance 'U_6' of 'and'
   dout1 <= a AND b;

   -- ModuleWare code(v1.9) for instance 'U_3' of 'or'
   cout <= dout OR dout1;

   -- Instance port mappings.
   U_0 : my_xor
      PORT MAP (
         a => a,
         b => b,
         f => f
      );
   U_1 : my_xor
      PORT MAP (
         a => f,
         b => cin,
         f => s
      );

END struct;
