-- VHDL Entity lab4_lib.my_xor.symbol
--
-- Created:
--          by - zhijiej2.ews (eceb-2022-28.ews.illinois.edu)
--          at - 17:21:56 09/18/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY my_xor IS
   PORT( 
      a : IN     std_logic;
      b : IN     std_logic;
      f : OUT    std_logic
   );

-- Declarations

END my_xor ;

--
-- VHDL Architecture lab4_lib.my_xor.struct
--
-- Created:
--          by - zhijiej2.ews (eceb-2022-28.ews.illinois.edu)
--          at - 17:21:56 09/18/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF my_xor IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'and'
   dout1 <= dout AND b;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'and'
   dout2 <= a AND dout3;

   -- ModuleWare code(v1.9) for instance 'U_2' of 'inv'
   dout <= NOT(a);

   -- ModuleWare code(v1.9) for instance 'U_4' of 'inv'
   dout3 <= NOT(b);

   -- ModuleWare code(v1.9) for instance 'U_3' of 'or'
   f <= dout1 OR dout2;

   -- Instance port mappings.

END struct;
