-- VHDL Entity lab8_lib.Next_State_Logic.symbol
--
-- Created:
--          by - zhijiej2.ews (dcl-l440-27.ews.illinois.edu)
--          at - 15:58:05 10/19/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Next_State_Logic IS
   PORT( 
      S0   : IN     std_logic;
      S1   : IN     std_logic;
      S2   : IN     std_logic;
      T    : IN     std_logic;
      S0_N : OUT    std_logic;
      S1_N : OUT    std_logic;
      S2_N : OUT    std_logic
   );

-- Declarations

END Next_State_Logic ;

--
-- VHDL Architecture lab8_lib.Next_State_Logic.struct
--
-- Created:
--          by - zhijiej2.ews (dcl-l440-27.ews.illinois.edu)
--          at - 15:58:05 10/19/16
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF Next_State_Logic IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;



BEGIN

   -- ModuleWare code(v1.9) for instance 'U_3' of 'and'
   S1_N <= S2 AND dout;

   -- ModuleWare code(v1.9) for instance 'U_4' of 'and'
   S0_N <= dout2 AND dout1;

   -- ModuleWare code(v1.9) for instance 'U_5' of 'and'
   S2_N <= T AND T;

   -- ModuleWare code(v1.9) for instance 'U_0' of 'inv'
   dout2 <= NOT(S2);

   -- ModuleWare code(v1.9) for instance 'U_1' of 'inv'
   dout1 <= NOT(S1);

   -- ModuleWare code(v1.9) for instance 'U_2' of 'inv'
   dout <= NOT(S0);

   -- Instance port mappings.

END struct;
